services:
  private-gpt:
    build:
#      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
    user: "1000:1000"
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
#    user: "1000:1000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
